# Generated by Django 4.1.1 on 2022-09-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='roles',
            field=models.CharField(choices=[('Arbitrator', 'Arbitrator'), ('Athlete', 'Athlete'), ('Coach', 'Coach'), ('Club', 'Club')], max_length=200, null=True),
        ),
    ]
