# Generated by Django 4.1.1 on 2022-09-26 10:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalback', '0002_role_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arbitrator',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('licence', models.IntegerField()),
                ('cin', models.IntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('sex', models.TextField()),
                ('birthday', models.DateField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('licence', models.IntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('sex', models.TextField()),
                ('category_id', models.IntegerField()),
                ('grade_id', models.IntegerField()),
                ('birthday', models.DateField()),
                ('id_degree', models.IntegerField()),
                ('cin', models.TextField(blank=True, null=True)),
                ('nationality', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='image/')),
                ('idantity_photo', models.ImageField(blank=True, null=True, upload_to='image/')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('licence', models.IntegerField()),
                ('cin', models.IntegerField()),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('sex', models.TextField()),
                ('birthday', models.DateField()),
                ('id_grade', models.TextField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('country', models.TextField()),
                ('state', models.TextField()),
                ('city', models.TextField()),
                ('address', models.TextField()),
                ('zip_code', models.IntegerField()),
                ('phone', models.CharField(max_length=200, null=True)),
                ('location', models.TextField()),
                ('arbitrator', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.arbitrator')),
                ('athlete', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.athlete')),
                ('club', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.club')),
                ('coach', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.coach')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.CreateModel(
            name='Supporter',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('profile', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.profile')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='role',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.profile'),
        ),
    ]
