# Generated by Django 4.1.1 on 2022-09-26 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0003_arbitrator_athlete_club_coach_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='arbitrator',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='athlete',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='club',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='role',
            name='profile',
        ),
        migrations.AddField(
            model_name='arbitrator',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.profile'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.profile'),
        ),
        migrations.AddField(
            model_name='club',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.profile'),
        ),
        migrations.AddField(
            model_name='coach',
            name='profile',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.role'),
        ),
    ]
