# Generated by Django 4.1.1 on 2022-09-26 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0004_remove_profile_arbitrator_remove_profile_athlete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporter',
            name='club',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.club'),
        ),
    ]
