# Generated by Django 4.1.1 on 2022-09-26 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0006_remove_profile_role_role_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='role',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roles',
            field=models.CharField(choices=[('Arbitrator', 'Arbitrator'), ('Athlete', 'Athlete'), ('Coach', 'Coach'), ('Club', 'Club'), ('Supporter', 'Supporter')], max_length=200, null=True),
        ),
    ]
