# Generated by Django 4.1.1 on 2022-09-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0010_alter_arbitrator_id_alter_athlete_id_alter_club_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arbitrator',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbitrator',
            name='cin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbitrator',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbitrator',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arbitrator',
            name='sex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='category_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='grade_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='id_degree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='nationality',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='sex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='cin',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='first_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='id_grade',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='last_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coach',
            name='sex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supporter',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
