# Generated by Django 4.1.1 on 2022-09-29 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finalback', '0011_alter_arbitrator_birthday_alter_arbitrator_cin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('categorie_age', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Grade', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Seasons', models.IntegerField()),
                ('activated', models.BooleanField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Weights',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('masse_en_killograme', models.IntegerField()),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.RemoveField(
            model_name='coach',
            name='id_grade',
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.role'),
        ),
        migrations.AlterField(
            model_name='role',
            name='roles',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='Licences',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_licences', models.IntegerField(blank=True, null=True)),
                ('activated', models.BooleanField(blank=True, null=True)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.role')),
                ('seasons', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.seasons')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='weights',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.weights'),
        ),
        migrations.AddField(
            model_name='coach',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.grade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='categorie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='finalback.categorie'),
        ),
        migrations.AddField(
            model_name='profile',
            name='licences',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='finalback.licences'),
        ),
    ]
