# Generated by Django 4.1.1 on 2022-09-30 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0012_categorie_grade_seasons_weights_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='licences',
            name='activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='Seasons',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='seasons',
            name='activated',
            field=models.BooleanField(default=False),
        ),
    ]
