# Generated by Django 4.1.1 on 2022-10-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalback', '0016_alter_categorie_categorie_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='Grade',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
